base_images:
  ubi-minimal:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
build_root:
  project_image:
    dockerfile_path: .openshift-ci/build/Dockerfile.build_root
images:
- build_args:
  - name: BUILDER_ROOT_DIR
    value: /go/src/github.com/stackrox/collector/builder
  dockerfile_path: builder/Dockerfile
  from: src
  to: collector-builder
- dockerfile_path: .openshift-ci/build/Dockerfile.build_collector
  from: collector-builder
  to: collector
- dockerfile_path: .openshift-ci/build/Dockerfile.drivers
  from: collector
  to: collector-drivers
- dockerfile_path: .openshift-ci/build/Dockerfile.create_bundle
  from: collector-drivers
  to: collector-bundle
- build_args:
  - name: ROOT_DIR
    value: /go/src/github.com/stackrox/collector/collector/container/rhel
  context_dir: collector/container/rhel
  dockerfile_path: collector/container/Dockerfile.gen
  from: ubi-minimal
  inputs:
    collector-bundle:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/stackrox/collector/.
  to: collector-full
- context_dir: .openshift-ci
  dockerfile_path: jobs/integration-tests/Dockerfile
  from: src
  to: integration-tests
promotion:
  namespace: stackrox
  tag: osci-test
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: lint
  steps:
    test:
    - as: clang-format
      commands: make -C collector check
      from: src
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
    - as: shfmt-check
      commands: make shfmt-check
      from: src
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
- as: test-scripts
  steps:
    test:
    - as: shellcheck-all
      commands: make shellcheck-all
      from: src
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
- as: push-images
  steps:
    test:
    - as: push-collector-images
      commands: .openshift-ci/jobs/push-images/push-images.sh
      credentials:
      - mount_path: /tmp/secret/stackrox-stackrox-push
        name: stackrox-stackrox-push
        namespace: test-credentials
      dependencies:
      - env: COLLECTOR_FULL
        name: collector-full
      from: src
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
- as: unit-tests
  steps:
    test:
    - as: collector-unit-tests
      commands: /go/src/github.com/stackrox/collector/cmake-build/collector/runUnitTests
      from: collector
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
- as: garden-linux-ebpf-integration-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      IMAGE_FAMILY: garden-linux
      IMAGE_NAME: gardenlinux-gcp-cloud-gardener--prod-576-9-229156
      VM_TYPE: garden-linux
    workflow: stackrox-collector-integration-tests
- as: garden-linux-kernel-module-integration-tests
  steps:
    env:
      COLLECTION_METHOD: kernel-module
      IMAGE_FAMILY: garden-linux
      IMAGE_NAME: gardenlinux-gcp-cloud-gardener--prod-576-9-229156
      VM_TYPE: garden-linux
    workflow: stackrox-collector-integration-tests
- as: rhel-7-ebpf-integration-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      IMAGE_FAMILY: rhel-7
      VM_TYPE: rhel
    workflow: stackrox-collector-integration-tests
- as: rhel-7-kernel-module-integration-tests
  steps:
    env:
      COLLECTION_METHOD: kernel-module
      IMAGE_FAMILY: rhel-7
      VM_TYPE: rhel
    workflow: stackrox-collector-integration-tests
- as: rhel-8-ebpf-integration-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      IMAGE_FAMILY: rhel-8
      VM_TYPE: rhel
    workflow: stackrox-collector-integration-tests
- as: rhel-8-kernel-module-integration-tests
  steps:
    env:
      COLLECTION_METHOD: kernel-module
      IMAGE_FAMILY: rhel-8
      VM_TYPE: rhel
    workflow: stackrox-collector-integration-tests
- as: cos-85-lts-ebpf-integration-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      IMAGE_FAMILY: cos-85-lts
      VM_TYPE: cos
    workflow: stackrox-collector-integration-tests
- as: cos-85-lts-kernel-module-integration-tests
  steps:
    env:
      COLLECTION_METHOD: kernel-module
      IMAGE_FAMILY: cos-85-lts
      VM_TYPE: cos
    workflow: stackrox-collector-integration-tests
- as: cos-89-lts-ebpf-integration-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      IMAGE_FAMILY: cos-89-lts
      VM_TYPE: cos
    workflow: stackrox-collector-integration-tests
- as: cos-89-lts-kernel-module-integration-tests
  steps:
    env:
      COLLECTION_METHOD: kernel-module
      IMAGE_FAMILY: cos-89-lts
      VM_TYPE: cos
    workflow: stackrox-collector-integration-tests
- as: cos-beta-ebpf-integration-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      IMAGE_FAMILY: cos-beta
      VM_TYPE: cos
    workflow: stackrox-collector-integration-tests
- as: cos-beta-kernel-module-integration-tests
  steps:
    env:
      COLLECTION_METHOD: kernel-module
      IMAGE_FAMILY: cos-beta
      VM_TYPE: cos
    workflow: stackrox-collector-integration-tests
- as: cos-dev-ebpf-integration-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      IMAGE_FAMILY: cos-dev
      VM_TYPE: cos
    workflow: stackrox-collector-integration-tests
- as: cos-dev-kernel-module-integration-tests
  steps:
    env:
      COLLECTION_METHOD: kernel-module
      IMAGE_FAMILY: cos-dev
      VM_TYPE: cos
    workflow: stackrox-collector-integration-tests
- as: cos-stable-ebpf-integration-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      IMAGE_FAMILY: cos-stable
      VM_TYPE: cos
    workflow: stackrox-collector-integration-tests
- as: cos-stable-kernel-module-integration-tests
  steps:
    env:
      COLLECTION_METHOD: kernel-module
      IMAGE_FAMILY: cos-stable
      VM_TYPE: cos
    workflow: stackrox-collector-integration-tests
- as: fedora-coreos-stable-ebpf-integration-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      IMAGE_FAMILY: fedora-coreos-stable
      VM_TYPE: fedora-coreos
    workflow: stackrox-collector-integration-tests
- as: fedora-coreos-stable-kernel-module-integration-tests
  steps:
    env:
      COLLECTION_METHOD: kernel-module
      IMAGE_FAMILY: fedora-coreos-stable
      VM_TYPE: fedora-coreos
    workflow: stackrox-collector-integration-tests
- as: sles-12-ebpf-integration-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      IMAGE_FAMILY: sles-12
      VM_TYPE: suse
    workflow: stackrox-collector-integration-tests
- as: sles-12-kernel-module-integration-tests
  steps:
    env:
      COLLECTION_METHOD: kernel-module
      IMAGE_FAMILY: sles-12
      VM_TYPE: suse
    workflow: stackrox-collector-integration-tests
- as: sles-15-ebpf-integration-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      IMAGE_FAMILY: sles-15
      VM_TYPE: suse
    workflow: stackrox-collector-integration-tests
- as: sles-15-kernel-module-integration-tests
  steps:
    env:
      COLLECTION_METHOD: kernel-module
      IMAGE_FAMILY: sles-15
      VM_TYPE: suse
    workflow: stackrox-collector-integration-tests
- as: ubuntu-1804-lts-ebpf-integration-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      IMAGE_FAMILY: ubuntu-1804-lts
      VM_TYPE: ubuntu-os
    workflow: stackrox-collector-integration-tests
- as: ubuntu-1804-lts-kernel-module-integration-tests
  steps:
    env:
      COLLECTION_METHOD: kernel-module
      IMAGE_FAMILY: ubuntu-1804-lts
      VM_TYPE: ubuntu-os
    workflow: stackrox-collector-integration-tests
- as: ubuntu-2004-lts-ebpf-integration-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      IMAGE_FAMILY: ubuntu-2004-lts
      VM_TYPE: ubuntu-os
    workflow: stackrox-collector-integration-tests
- as: ubuntu-2004-lts-kernel-module-integration-tests
  steps:
    env:
      COLLECTION_METHOD: kernel-module
      IMAGE_FAMILY: ubuntu-2004-lts
      VM_TYPE: ubuntu-os
    workflow: stackrox-collector-integration-tests
- as: ubuntu-2204-lts-ebpf-integration-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      IMAGE_FAMILY: ubuntu-2204-lts
      VM_TYPE: ubuntu-os
    workflow: stackrox-collector-integration-tests
- as: ubuntu-2204-lts-kernel-module-integration-tests
  steps:
    env:
      COLLECTION_METHOD: kernel-module
      IMAGE_FAMILY: ubuntu-2204-lts
      VM_TYPE: ubuntu-os
    workflow: stackrox-collector-integration-tests
- as: ubuntu-pro-1804-lts-ebpf-integration-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      IMAGE_FAMILY: ubuntu-pro-1804-lts
      VM_TYPE: ubuntu-os-pro
    workflow: stackrox-collector-integration-tests
- as: ubuntu-pro-1804-lts-kernel-module-integration-tests
  steps:
    env:
      COLLECTION_METHOD: kernel-module
      IMAGE_FAMILY: ubuntu-pro-1804-lts
      VM_TYPE: ubuntu-os-pro
    workflow: stackrox-collector-integration-tests
- as: flatcar-stable-ebpf-integration-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      IMAGE_FAMILY: flatcar-stable
      VM_TYPE: flatcar
    workflow: stackrox-collector-integration-tests
- as: flatcar-stable-kernel-module-integration-tests
  steps:
    env:
      COLLECTION_METHOD: kernel-module
      IMAGE_FAMILY: flatcar-stable
      VM_TYPE: flatcar
    workflow: stackrox-collector-integration-tests
zz_generated_metadata:
  branch: ROX-11222-collector-integration-test
  org: stackrox
  repo: collector
